package amf_message

type Event int

const (
	EventNGAPMessage Event = iota
	EventNGAPAcceptConn
	EventNGAPCloseConn
	EventN1N2MessageTransferStatus
	EventProvideDomainSelectionInfo
	EventProvideLocationInfo
	EventN1N2MessageSubscribe
	EventN1N2MessageUnSubscribe
	EventSmContextStatusNotify
	EventGMMT3513
	EventGMMT3565
	EventGMMT3560ForAuthenticationRequest
	EventGMMT3560ForSecurityModeCommand
	EventGMMT3550
	EventGMMT3522
	EventAmPolicyControlUpdateNotifyUpdate
	EventAmPolicyControlUpdateNotifyTerminate
	EventOAMRegisteredUEContext
	EventN1MessageNotify
)
