/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package communication

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi/models"
	"free5gc/src/amf/logger"
	"free5gc/src/amf/producer"
	"github.com/gin-gonic/gin"
	"net/http"
)

// AMFStatusChangeSubscribe - Namf_Communication AMF Status Change Subscribe service Operation
func AMFStatusChangeSubscribe(c *gin.Context) {
	var subscriptionData models.SubscriptionData
	err := c.ShouldBindJSON(&subscriptionData)
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.CommLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := http_wrapper.NewRequest(c.Request, subscriptionData)
	rsp := producer.HandleAMFStatusChangeSubscribeRequest(req)

	for key, val := range rsp.Header {
		c.Header(key, val[0])
	}

	c.JSON(rsp.Status, rsp.Body)
}
